name: Deploy Astro to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to desarrollo.intercacao.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd desarrollo.intercacao.com
            git pull origin main
            npm install
            npm run build
            pm2 restart astro
